### ISSUE TITLE
Fascinating!

### ISSUE THREAD

**Issue by PySimpleGUI** [spaceymonk/morse-analyzer#1]
I would love to see a screenshot if you've got a moment to take one and toss it into your readme.

The name of your repo immediately grabbed my attention.  I used to listen to shortwave quite a bit when I was young.  

Are you able to use your tool with signals you pick up from the radio waves?  What do you decode with it???

**Comment by PySimpleGUI** [comment]
Oh wow!  Thanks for the screenshot and added intro!  I had no clue it was this sophisticated.  If you have a  moment, I'm sure, SURE, other PySimpleGUI users would love to see this.  Issue # 10 on the PySimpleGUI repo is a user screenshots issue.   I would like to include your screenshot in the next announcement as a  "highlighted project".  Great stuff to see!

**Comment by spaceymonk** [comment]
@PySimpleGUI First of all, I'm glad you like my project.

This is my first GUI application on Python and I did not want it to become a complex project. I was experimenting on *Jupyter Notebook* but I had to scroll all the time 😄 (`ipywidgets` was helping though). So, after a little search, I came across PySimpleGUI and it was **really** simple. I mean, it is simple in both logic and code. I genuinely appreciate the work you have done. 💯 

About the program, as you have seen from the video, it can decode Morse codes from audio files. Computer-generated Morse is easier to decode due to stable WPM but with some tweaks, it can decode human-generated ones too (something similar shown in the video).

I would be happy to be included in such a collaboration. But, I must say, I do not think about spending more time on this project.

Thank you again!

**Comment by PySimpleGUI** [comment]
> This is my first GUI application on Python and I did not want it to become a complex project.

I find this a stunning statement on many levels.  This is not what I would consider being a simple project or one that is not complex.  It's really incredible in appearance and functionality.  Wow... just... WOW....

> I do not think about spending more time on this project.

I like this!  When you've solved the problem to your satisfaction and have moved on and don't care to return to it, that's the ultimate success in my opinion.  I like to solve a problem and move on.  Building more flexibility than you **know** you'll need can be wasteful and costly.  It's what I call "overbuilding".  It's building for a tomorrow that is never going to arrive. 

> I genuinely appreciate the work you have done. 

Thank you so so much for this.  I genuinely find great inspiration in looking at users' projects.  It's why I stopped in to see your project.  I appreciate you taking the time to post a screenshot and explain the background and how you see the future of the project too.  Really is a fantastic conversation to get to have with another developer.
